// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: leankg/v1/leankg.proto

package leankgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`   // repo | dir | memory
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`       // repo/dir target or memory file path
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // memory write command (action=memory)
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{0}
}

func (x *ImportRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ImportRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImportRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ImportRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // core result payload (JSON-encoded map; stable shape = MCP text content)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{1}
}

func (x *ImportResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "" = ladder router; exact|fuzzy|semantic|element|impact|path|callers|callees|context|explain|memory
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // action params (e.g. path.to=<qn>)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type MemoryReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // view | snapshot | search
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryReadRequest) Reset() {
	*x = MemoryReadRequest{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryReadRequest) ProtoMessage() {}

func (x *MemoryReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryReadRequest.ProtoReflect.Descriptor instead.
func (*MemoryReadRequest) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryReadRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MemoryReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MemoryReadRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MemoryReadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MemoryReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryReadResponse) Reset() {
	*x = MemoryReadResponse{}
	mi := &file_leankg_v1_leankg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryReadResponse) ProtoMessage() {}

func (x *MemoryReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leankg_v1_leankg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryReadResponse.ProtoReflect.Descriptor instead.
func (*MemoryReadResponse) Descriptor() ([]byte, []int) {
	return file_leankg_v1_leankg_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryReadResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_leankg_v1_leankg_proto protoreflect.FileDescriptor

const file_leankg_v1_leankg_proto_rawDesc = "" +
	"\n" +
	"\x16leankg/v1/leankg.proto\x12\tleankg.v1\"\xc6\x01\n" +
	"\rImportRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x126\n" +
	"\x04args\x18\x04 \x03(\v2\".leankg.v1.ImportRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x0eImportResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\xc2\x01\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x125\n" +
	"\x04args\x18\x04 \x03(\v2!.leankg.v1.QueryRequest.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\rQueryResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\x0f\n" +
	"\rStatusRequest\"$\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"m\n" +
	"\x11MemoryReadRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"(\n" +
	"\x12MemoryReadResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json2\x8d\x02\n" +
	"\x06LeanKG\x12=\n" +
	"\x06Import\x12\x18.leankg.v1.ImportRequest\x1a\x19.leankg.v1.ImportResponse\x12:\n" +
	"\x05Query\x12\x17.leankg.v1.QueryRequest\x1a\x18.leankg.v1.QueryResponse\x12=\n" +
	"\x06Status\x12\x18.leankg.v1.StatusRequest\x1a\x19.leankg.v1.StatusResponse\x12I\n" +
	"\n" +
	"MemoryRead\x12\x1c.leankg.v1.MemoryReadRequest\x1a\x1d.leankg.v1.MemoryReadResponseB?Z=github.com/FreePeak/LeanKG/go/internal/rpc/leankg/v1;leankgv1b\x06proto3"

var (
	file_leankg_v1_leankg_proto_rawDescOnce sync.Once
	file_leankg_v1_leankg_proto_rawDescData []byte
)

func file_leankg_v1_leankg_proto_rawDescGZIP() []byte {
	file_leankg_v1_leankg_proto_rawDescOnce.Do(func() {
		file_leankg_v1_leankg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leankg_v1_leankg_proto_rawDesc), len(file_leankg_v1_leankg_proto_rawDesc)))
	})
	return file_leankg_v1_leankg_proto_rawDescData
}

var file_leankg_v1_leankg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_leankg_v1_leankg_proto_goTypes = []any{
	(*ImportRequest)(nil),      // 0: leankg.v1.ImportRequest
	(*ImportResponse)(nil),     // 1: leankg.v1.ImportResponse
	(*QueryRequest)(nil),       // 2: leankg.v1.QueryRequest
	(*QueryResponse)(nil),      // 3: leankg.v1.QueryResponse
	(*StatusRequest)(nil),      // 4: leankg.v1.StatusRequest
	(*StatusResponse)(nil),     // 5: leankg.v1.StatusResponse
	(*MemoryReadRequest)(nil),  // 6: leankg.v1.MemoryReadRequest
	(*MemoryReadResponse)(nil), // 7: leankg.v1.MemoryReadResponse
	nil,                        // 8: leankg.v1.ImportRequest.ArgsEntry
	nil,                        // 9: leankg.v1.QueryRequest.ArgsEntry
}
var file_leankg_v1_leankg_proto_depIdxs = []int32{
	8, // 0: leankg.v1.ImportRequest.args:type_name -> leankg.v1.ImportRequest.ArgsEntry
	9, // 1: leankg.v1.QueryRequest.args:type_name -> leankg.v1.QueryRequest.ArgsEntry
	0, // 2: leankg.v1.LeanKG.Import:input_type -> leankg.v1.ImportRequest
	2, // 3: leankg.v1.LeanKG.Query:input_type -> leankg.v1.QueryRequest
	4, // 4: leankg.v1.LeanKG.Status:input_type -> leankg.v1.StatusRequest
	6, // 5: leankg.v1.LeanKG.MemoryRead:input_type -> leankg.v1.MemoryReadRequest
	1, // 6: leankg.v1.LeanKG.Import:output_type -> leankg.v1.ImportResponse
	3, // 7: leankg.v1.LeanKG.Query:output_type -> leankg.v1.QueryResponse
	5, // 8: leankg.v1.LeanKG.Status:output_type -> leankg.v1.StatusResponse
	7, // 9: leankg.v1.LeanKG.MemoryRead:output_type -> leankg.v1.MemoryReadResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_leankg_v1_leankg_proto_init() }
func file_leankg_v1_leankg_proto_init() {
	if File_leankg_v1_leankg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leankg_v1_leankg_proto_rawDesc), len(file_leankg_v1_leankg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leankg_v1_leankg_proto_goTypes,
		DependencyIndexes: file_leankg_v1_leankg_proto_depIdxs,
		MessageInfos:      file_leankg_v1_leankg_proto_msgTypes,
	}.Build()
	File_leankg_v1_leankg_proto = out.File
	file_leankg_v1_leankg_proto_goTypes = nil
	file_leankg_v1_leankg_proto_depIdxs = nil
}
