// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: leankg/v1/leankg.proto

package leankgv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/FreePeak/LeanKG/go/internal/rpc/leankg/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LeanKGName is the fully-qualified name of the LeanKG service.
	LeanKGName = "leankg.v1.LeanKG"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LeanKGImportProcedure is the fully-qualified name of the LeanKG's Import RPC.
	LeanKGImportProcedure = "/leankg.v1.LeanKG/Import"
	// LeanKGQueryProcedure is the fully-qualified name of the LeanKG's Query RPC.
	LeanKGQueryProcedure = "/leankg.v1.LeanKG/Query"
	// LeanKGStatusProcedure is the fully-qualified name of the LeanKG's Status RPC.
	LeanKGStatusProcedure = "/leankg.v1.LeanKG/Status"
	// LeanKGMemoryReadProcedure is the fully-qualified name of the LeanKG's MemoryRead RPC.
	LeanKGMemoryReadProcedure = "/leankg.v1.LeanKG/MemoryRead"
)

// LeanKGClient is a client for the leankg.v1.LeanKG service.
type LeanKGClient interface {
	// Import indexes repositories/directories or curates memory (write actions).
	Import(context.Context, *connect.Request[v1.ImportRequest]) (*connect.Response[v1.ImportResponse], error)
	// Query runs the L0-L3 ladder or pinned rungs (read).
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error)
	// Status reports health, inventory, freshness, embed state (read).
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// MemoryRead handles memory view/snapshot/search (read).
	MemoryRead(context.Context, *connect.Request[v1.MemoryReadRequest]) (*connect.Response[v1.MemoryReadResponse], error)
}

// NewLeanKGClient constructs a client for the leankg.v1.LeanKG service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLeanKGClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LeanKGClient {
	baseURL = strings.TrimRight(baseURL, "/")
	leanKGMethods := v1.File_leankg_v1_leankg_proto.Services().ByName("LeanKG").Methods()
	return &leanKGClient{
		_import: connect.NewClient[v1.ImportRequest, v1.ImportResponse](
			httpClient,
			baseURL+LeanKGImportProcedure,
			connect.WithSchema(leanKGMethods.ByName("Import")),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+LeanKGQueryProcedure,
			connect.WithSchema(leanKGMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+LeanKGStatusProcedure,
			connect.WithSchema(leanKGMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		memoryRead: connect.NewClient[v1.MemoryReadRequest, v1.MemoryReadResponse](
			httpClient,
			baseURL+LeanKGMemoryReadProcedure,
			connect.WithSchema(leanKGMethods.ByName("MemoryRead")),
			connect.WithClientOptions(opts...),
		),
	}
}

// leanKGClient implements LeanKGClient.
type leanKGClient struct {
	_import    *connect.Client[v1.ImportRequest, v1.ImportResponse]
	query      *connect.Client[v1.QueryRequest, v1.QueryResponse]
	status     *connect.Client[v1.StatusRequest, v1.StatusResponse]
	memoryRead *connect.Client[v1.MemoryReadRequest, v1.MemoryReadResponse]
}

// Import calls leankg.v1.LeanKG.Import.
func (c *leanKGClient) Import(ctx context.Context, req *connect.Request[v1.ImportRequest]) (*connect.Response[v1.ImportResponse], error) {
	return c._import.CallUnary(ctx, req)
}

// Query calls leankg.v1.LeanKG.Query.
func (c *leanKGClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error) {
	return c.query.CallUnary(ctx, req)
}

// Status calls leankg.v1.LeanKG.Status.
func (c *leanKGClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// MemoryRead calls leankg.v1.LeanKG.MemoryRead.
func (c *leanKGClient) MemoryRead(ctx context.Context, req *connect.Request[v1.MemoryReadRequest]) (*connect.Response[v1.MemoryReadResponse], error) {
	return c.memoryRead.CallUnary(ctx, req)
}

// LeanKGHandler is an implementation of the leankg.v1.LeanKG service.
type LeanKGHandler interface {
	// Import indexes repositories/directories or curates memory (write actions).
	Import(context.Context, *connect.Request[v1.ImportRequest]) (*connect.Response[v1.ImportResponse], error)
	// Query runs the L0-L3 ladder or pinned rungs (read).
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error)
	// Status reports health, inventory, freshness, embed state (read).
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// MemoryRead handles memory view/snapshot/search (read).
	MemoryRead(context.Context, *connect.Request[v1.MemoryReadRequest]) (*connect.Response[v1.MemoryReadResponse], error)
}

// NewLeanKGHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLeanKGHandler(svc LeanKGHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	leanKGMethods := v1.File_leankg_v1_leankg_proto.Services().ByName("LeanKG").Methods()
	leanKGImportHandler := connect.NewUnaryHandler(
		LeanKGImportProcedure,
		svc.Import,
		connect.WithSchema(leanKGMethods.ByName("Import")),
		connect.WithHandlerOptions(opts...),
	)
	leanKGQueryHandler := connect.NewUnaryHandler(
		LeanKGQueryProcedure,
		svc.Query,
		connect.WithSchema(leanKGMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	leanKGStatusHandler := connect.NewUnaryHandler(
		LeanKGStatusProcedure,
		svc.Status,
		connect.WithSchema(leanKGMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	leanKGMemoryReadHandler := connect.NewUnaryHandler(
		LeanKGMemoryReadProcedure,
		svc.MemoryRead,
		connect.WithSchema(leanKGMethods.ByName("MemoryRead")),
		connect.WithHandlerOptions(opts...),
	)
	return "/leankg.v1.LeanKG/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LeanKGImportProcedure:
			leanKGImportHandler.ServeHTTP(w, r)
		case LeanKGQueryProcedure:
			leanKGQueryHandler.ServeHTTP(w, r)
		case LeanKGStatusProcedure:
			leanKGStatusHandler.ServeHTTP(w, r)
		case LeanKGMemoryReadProcedure:
			leanKGMemoryReadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLeanKGHandler returns CodeUnimplemented from all methods.
type UnimplementedLeanKGHandler struct{}

func (UnimplementedLeanKGHandler) Import(context.Context, *connect.Request[v1.ImportRequest]) (*connect.Response[v1.ImportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("leankg.v1.LeanKG.Import is not implemented"))
}

func (UnimplementedLeanKGHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("leankg.v1.LeanKG.Query is not implemented"))
}

func (UnimplementedLeanKGHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("leankg.v1.LeanKG.Status is not implemented"))
}

func (UnimplementedLeanKGHandler) MemoryRead(context.Context, *connect.Request[v1.MemoryReadRequest]) (*connect.Response[v1.MemoryReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("leankg.v1.LeanKG.MemoryRead is not implemented"))
}
