#!/usr/bin/env python3
"""Deterministic nested multi-repo workspace generator for scale testing.

Emits a workspace that mirrors the shapes LeanKG's scale machinery actually
has to handle — the things a flat fixture cannot test:

  * nested git repos at varying depths (git_workspace.rs caps at depth 4)
  * a non-git workspace root containing them (polyrepo mount shape)
  * noise directories (node_modules/, target/, dist/) the walker must skip
  * cross-file call edges so the relationship graph is non-trivial
  * mixed languages (Rust + TypeScript) for multi-parser coverage

Content is fully deterministic (no timestamps, no randomness) so index
timings and element counts are comparable across runs and machines.

Usage:
  gen_scale_fixture.py <out_dir> [--repos N] [--files-per-repo M] [--noise]

Layout produced (default 4 repos, 60 files each):
  <out_dir>/                 workspace root (NOT a git repo)
    app-a/                   depth-1 repo   (.git + M files)
    app-b/                   depth-1 repo
    platform/svc-c/          depth-3 repo
    platform/svc-d/          depth-3 repo
    noise/                   (with --noise) node_modules/target/dist decoys
"""
import argparse
import subprocess
import sys
from pathlib import Path


def rust_module(repo: str, i: int) -> str:
    """One Rust module: a struct, 8 methods, and cross-file calls.

    Calls target the previous module in the same repo (stable edges) plus a
    fixed cross-repo edge into app-a so the workspace graph is connected.
    """
    prev = f"m{(i - 1) % 60:02d}"
    fns = "\n".join(
        f"    pub fn op_{j}(&self, x: u32) -> u32 {{ x.wrapping_add({i * 31 + j}) }}"
        for j in range(8)
    )
    calls = "\n".join(
        f"        let _ = super::{prev}::Thing::default().op_{j}(1);" for j in range(8)
    )
    cross = (
        "        let _ = crate::m00::Thing::default().op_0(1);"
        if repo != "app-a" and i == 7
        else ""
    )
    return f"""//! Fixture module {i} in {repo} (deterministic; generated by gen_scale_fixture.py)

pub struct Thing {{ pub id: u32 }}

impl Default for Thing {{
    fn default() -> Self {{ Thing {{ id: {i} }} }}
}}

impl Thing {{
{fns}

    pub fn run(&self) -> u32 {{
{calls}
{cross}
        self.id
    }}
}}
"""


def ts_module(repo: str, i: int) -> str:
    """TypeScript counterpart so multi-language parsing is exercised."""
    return f"""// Fixture module {i} in {repo} (deterministic)
export interface Spec{i} {{ id: number; name: string }}

export function build{i}(count: number): Spec{i}[] {{
  return Array.from({{ length: count }}, (_, k) => ({{ id: k, name: "{repo}-{i}-" + k }}));
}}

export function consume{i}(specs: Spec{i}[]): number {{
  return specs.reduce((a, s) => a + s.id, {i});
}}
"""


def git_commit(repo: Path, msg: str) -> None:
    env = {
        "GIT_AUTHOR_NAME": "fixture", "GIT_AUTHOR_EMAIL": "f@x",
        "GIT_AUTHOR_DATE": "2020-01-01T00:00:00+0000",
        "GIT_COMMITTER_NAME": "fixture", "GIT_COMMITTER_EMAIL": "f@x",
        "GIT_COMMITTER_DATE": "2020-01-01T00:00:00+0000",
        "PATH": "/usr/bin:/bin", "HOME": str(repo),
    }
    for cmd in (["git", "init", "-q"], ["git", "add", "-A"], ["git", "commit", "-q", "-m", msg]):
        subprocess.run(cmd, cwd=repo, env=env, check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir")
    ap.add_argument("--repos", type=int, default=4)
    ap.add_argument("--files-per-repo", type=int, default=60)
    ap.add_argument("--noise", action="store_true",
                    help="add node_modules/target/dist decoy directories")
    a = ap.parse_args()

    root = Path(a.out_dir).resolve()
    if root.exists() and any(root.iterdir()):
        print(f"refusing to write into non-empty dir: {root}", file=sys.stderr)
        return 1
    root.mkdir(parents=True, exist_ok=True)

    # Repo placement alternates depth-1 and depth-3 to cover the nested-git
    # discovery walk (NESTED_GIT_MAX_DEPTH = 4).
    names = ["app-a", "app-b", "platform/svc-c", "platform/svc-d",
             "platform/svc-e", "tools/fx", "platform/deep/nest/g", "extra"]
    if a.repos > len(names):
        print(f"--repos {a.repos} exceeds {len(names)} unique placement slots "
              f"(would re-init the same directory)", file=sys.stderr)
        return 1
    repos = [root / names[k] for k in range(a.repos)]

    for r_i, repo in enumerate(repos):
        src = repo / "src"
        src.mkdir(parents=True, exist_ok=True)
        for i in range(a.files_per_repo):
            (src / f"m{i:02d}.rs").write_text(rust_module(repo.name, i))
            if i % 5 == 0:  # ~20% TypeScript
                (src / f"s{i:02d}.ts").write_text(ts_module(repo.name, i))
        (repo / "mod.rs").write_text(
            "\n".join(f"pub mod m{i:02d};" for i in range(a.files_per_repo)) + "\n")
        (repo / "README.md").write_text(f"# {repo.name}\n\nScale fixture repo {r_i}.\n")
        git_commit(repo, f"fixture {repo.name}")

    if a.noise:
        # Decoys the walker MUST skip: fake sources under excluded dirs.
        for d in ("node_modules/pkg", "target/debug", "dist", "vendor/x"):
            p = root / "noise" / d
            p.mkdir(parents=True, exist_ok=True)
            (p / "should_not_be_indexed.rs").write_text("pub fn NOISE() {}\n")

    # Manifest: repo rel-paths (one per line) so consumers never hardcode names.
    (root / ".fixture-manifest").write_text(
        "\n".join(str(r.relative_to(root)) for r in repos) + "\n")

    total_files = sum(
        len(list((r / "src").glob("*"))) for r in repos
    )
    print(f"workspace={root} repos={len(repos)} source_files={total_files}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
