#!/usr/bin/env bash
# quickstart_smoke.sh — H5 / FR-PLG-7: timed "< 5 min to first query result" smoke.
#
# Simulates a brand-new user end-to-end against LEANKG_PG_URL:
#   init -> migrate -> index -> mcp-http up -> first search_code hit -> doctor -> cleanup
#
# Usage:
#   set -a; source .env; set +a          # provides LEANKG_PG_URL (remote PG; never Docker locally)
#   scripts/quickstart_smoke.sh
#
# Env:
#   LEANKG_PG_URL            required in real mode (Postgres only, no Docker)
#   QUICKSTART_DRY_RUN=1     print the step plan without executing anything
#   QUICKSTART_SMOKE_PORT    MCP HTTP port (default 9711)
#   QUICKSTART_BUDGET        wall-clock budget seconds (default 300)
#
# Exit codes: 0 = pass (< budget), 1 = over budget, 2 = setup/step error.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT="${QUICKSTART_SMOKE_PORT:-9711}"
TIME_BUDGET=300
TIME_BUDGET="${QUICKSTART_BUDGET:-$TIME_BUDGET}"
DRY_RUN="${QUICKSTART_DRY_RUN:-0}"
SCRATCH="/tmp/opencode/qs-smoke-$$"
BASE_URL="http://127.0.0.1:$PORT"
SERVER_PID=""
TIMES=()   # "name|seconds" rows

# Resolve target/release/leankg honoring CARGO_TARGET_DIR and a global
# ~/.cargo/config.toml target-dir override (worktrees share one cache dir).
resolve_binary() {
    local cfg_target="" b
    if [ -f "$HOME/.cargo/config.toml" ]; then
        cfg_target="$(sed -n 's/^[[:space:]]*target-dir[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' "$HOME/.cargo/config.toml" | head -1)"
    fi
    local candidates=(
        "${CARGO_TARGET_DIR:+$CARGO_TARGET_DIR/release/leankg}"
        "${cfg_target:+$cfg_target/release/leankg}"
        "$REPO_ROOT/target/release/leankg"
    )
    for b in "${candidates[@]}"; do
        if [ -n "$b" ] && [ -x "$b" ]; then
            printf '%s\n' "$b"
            return 0
        fi
    done
    return 1
}
BINARY="$(resolve_binary || true)"

log()  { printf '%s\n' "$*"; }
err()  { printf '%s\n' "$*" >&2; }

now_s() { python3 -c 'import time; print(f"{time.time():.3f}")'; }

record() { TIMES+=("$1|$2"); }
row()    { printf '%s\n' "$1"; }

print_table() {
    log "--------------------------------------------"
    log "quickstart smoke — step timings"
    for t in "${TIMES[@]}"; do
        local name="${t%%|*}" secs="${t##*|}"
        printf '%-28s|%10s s\n' "$name" "$secs"
    done
    printf '%-28s|%10s s\n' "TOTAL" "${TOTAL_SECS:-?}"
    log "--------------------------------------------"
}

fail_setup() {
    err "SETUP ERROR: $*"
    cleanup_server
    exit 2
}

cleanup_server() {
    if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    SERVER_PID=""
}
trap cleanup_server EXIT INT TERM

timed_step() {
    # timed_step <name> <cmd...> — records seconds; setup-error on failure
    local name="$1"; shift
    local t0 t1 rc
    t0=$(now_s)
    "$@"; rc=$?
    t1=$(now_s)
    [ $rc -eq 0 ] || fail_setup "step '$name' failed with rc=$rc"
    record "$name" "$(python3 -c "print(f'{$t1-$t0:.3f}')")"
}

dry_run_plan() {
    log "QUICKSTART_DRY_RUN=1 — plan only, nothing executed"
    log "scratch dir would be: $SCRATCH"
    log "binary:               $BINARY"
    log "port:                 $PORT   budget: ${TIME_BUDGET}s"
    log "--------------------------------------------"
    record "init"        "-"
    record "migrate"     "-"
    record "index"       "-"
    record "server_up"   "-"
    record "first_query" "-"
    record "doctor"      "-"
    record "cleanup"     "-"
    TOTAL_SECS="-"
    print_table
    exit 0
}

# ---------------------------------------------------------------- dry run out
if [ "$DRY_RUN" = "1" ]; then
    dry_run_plan
fi

# ---------------------------------------------------------------- preflight
command -v python3 >/dev/null 2>&1 || fail_setup "python3 is required for timing/json checks"
command -v curl    >/dev/null 2>&1 || fail_setup "curl is required"
[ -n "${LEANKG_PG_URL:-}" ]       || fail_setup "LEANKG_PG_URL not set (source your .env: set -a; source .env; set +a)"

if [ -z "$BINARY" ]; then
    log "binary not found — building once (cargo build --release)..."
    (cd "$REPO_ROOT" && cargo build --release) || fail_setup "cargo build --release failed"
    BINARY="$(resolve_binary || true)"
fi
[ -n "$BINARY" ] && [ -x "$BINARY" ] || fail_setup "no executable leankg binary (resolved: '$BINARY')"

mkdir -p /tmp/opencode || fail_setup "cannot create /tmp/opencode"

T_START=$(now_s)
log "scratch project: $SCRATCH"

# ---------------------------------------------------------------- step 1: fixture + init
gen_fixture() {
    mkdir -p "$SCRATCH/src"
    for i in $(seq -w 0 9); do
        cat > "$SCRATCH/src/fnstore_${i}.rs" <<EOF
//! Quickstart fixture module ${i} (deterministic, generated by quickstart_smoke.sh).

pub struct FnStore${i} {
    pub id: u32,
    pub label: String,
}

impl FnStore${i} {
    pub fn fnconfig_new_${i}(id: u32) -> Self {
        Self { id, label: format!("fnstore-${i}-{}", id) }
    }

    pub fn fnlookup_${i}(&self, key: &str) -> Option<String> {
        if key.is_empty() { None } else { Some(self.label.clone()) }
    }
}

pub fn fntransform_${i}(input: &str) -> String {
    let store = FnStore${i}::fnconfig_new_${i}(input.len() as u32);
    store.fnlookup_${i}(input).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn fnroundtrip_${i}() {
        assert!(fntransform_${i}("x").contains("${i}"));
    }
}
EOF
    done
}
export -f gen_fixture
export SCRATCH BINARY
timed_step "init" bash -c "gen_fixture && cd '$SCRATCH' && '$BINARY' init"

# ---------------------------------------------------------------- step 2: migrate
timed_step "migrate" "$BINARY" migrate

# ---------------------------------------------------------------- step 3: index
# Run from the scratch dir: doc indexing scans a CWD-relative ./docs
# (src/main.rs), which must not pick up the invoking repo's docs/.
timed_step "index" bash -c "cd '$SCRATCH' && '$BINARY' index '$SCRATCH/src'"

# ---------------------------------------------------------------- step 4: server up + health
t0=$(now_s)
# --project must match the root the indexer keyed its PG schema from
# (<scratch>/src, since index was called with that path) or queries hit an
# empty sibling schema and return 0 elements.
( cd "$SCRATCH" && exec "$BINARY" mcp-http --port "$PORT" --project "$SCRATCH/src" ) >"/tmp/opencode/qs-smoke-$$-mcp.log" 2>&1 &
SERVER_PID=$!
HEALTHY=0
for _ in $(seq 1 60); do
    CODE="$(curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/health" 2>/dev/null || true)"
    if [ "$CODE" = "200" ]; then HEALTHY=1; break; fi
    kill -0 "$SERVER_PID" 2>/dev/null || fail_setup "mcp-http died during startup (see /tmp/opencode/qs-smoke-$$-mcp.log)"
    sleep 1
done
t1=$(now_s)
[ "$HEALTHY" = "1" ] || fail_setup "server /health never returned 200 within 60s"
record "server_up" "$(python3 -c "print(f'{$t1-$t0:.3f}')")"

# ---------------------------------------------------------------- step 5: first query
query_first() {
    local payload resp
    payload='{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"search_code","arguments":{"query":"fn"}}}'
    resp="$(curl -s -X POST "$BASE_URL/mcp?project=$SCRATCH/src" \
        -H 'Content-Type: application/json' \
        -H 'Accept: application/json, text/event-stream' \
        --max-time 60 \
        -d "$payload")"
    printf '%s' "$resp" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
except Exception as e:
    sys.exit(f"invalid JSON-RPC response: {e}")
if d.get("error"):
    sys.exit("JSON-RPC error: " + json.dumps(d["error"]))
r = d.get("result", {})
if r.get("isError"):
    sys.exit("tool reported isError=true")
text = "".join(c.get("text", "") for c in r.get("content", []) if isinstance(c, dict))
if not text.strip():
    sys.exit("empty result — expected >=1 element")
if "fn" not in text.lower():
    sys.exit("result does not reference indexed symbols")
print(text.splitlines()[0][:100])
'
}
timed_step "first_query" query_first

# ---------------------------------------------------------------- step 6: doctor
timed_step "doctor" "$BINARY" doctor

# ---------------------------------------------------------------- step 7: cleanup
t0=$(now_s)
cleanup_server
# Scratch schema drop: the per-project schema name is a SipHash of the project path
# (src/db/backend.rs::schema_for_path) and no leankg CLI exposes a drop command,
# so the scratch schema `leankg_p_*` is left in remote PG. Harmless (~10 elements).
record_note="left"
t1=$(now_s)
record "cleanup" "$(python3 -c "print(f'{$t1-$t0:.3f}')")"

# ---------------------------------------------------------------- verdict
T_END=$(now_s)
TOTAL_SECS="$(python3 -c "print(f'{$T_END-$T_START:.3f}')")"
print_table

OVER=$(python3 -c "print(1 if $TOTAL_SECS > $TIME_BUDGET else 0)")
if [ "$OVER" = "1" ]; then
    err "FAIL: total ${TOTAL_SECS}s exceeds ${TIME_BUDGET}s budget"
    log "note: scratch PG schema leankg_p_* left in place (no CLI exposes schema drop)"
    exit 1
fi
log "PASS: first query result in ${TOTAL_SECS}s (< ${TIME_BUDGET}s)"
log "note: scratch PG schema leankg_p_* left in place (no CLI exposes schema drop)"
exit 0
